# Generated by Django 3.1.7 on 2021-04-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=64, unique=True)),
                ('subject', models.CharField(blank=True, default='', max_length=64)),
                ('text', models.TextField(max_length=700)),
            ],
        ),
    ]
