# Generated by Django 3.1.7 on 2021-04-18 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('biodata', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=17, unique=True)),
                ('image', models.ImageField(upload_to='realtor/')),
                ('top_seller', models.BooleanField(default=False)),
                ('date_hired', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
